### ISSUE TITLE
plasma-ui: Sidebar ( PLASMA-1630 )

### ISSUE THREAD

**Issue by DetiToDeti** [salute-developers/plasma#113]
предлагается дополнить библиотеку компонентом Sidebar и увязать работу с ним таких компонентов как Gallery и тп по аналогии с react-pro-sidebar
Это упростит разработку интерфейсов в стиле в тч sberPortal

**Comment by Yeti-or** [comment]
Идея хорошая, надо подумать как это должно выглядеть с точки зрения нашего дизайна

**Comment by DetiToDeti** [comment]
у sberBox на главном экране наверху иконки, которые управляют галереей из квадратных и прямоугольных элементов, а у sberPortal аналогичные иконки слева. Вот такие панельки с иконками и галерея была бы очень полезна

**Comment by DetiToDeti** [comment]
<img width="960" alt="wellbell 321e07c 1920" src="https://user-images.githubusercontent.com/91261759/182312683-3dc42f1c-0100-499a-b4f7-4f056cb3e8d2.png">

Источник
https://developers.sber.ru/docs/ru/va/how-to/monetization/examples

**Comment by Yeti-or** [comment]
Думаю мы можем для начала сделать это в plasma-ui

**Comment by Yeti-or** [comment]
не доберемся
