### ISSUE TITLE
plasma-web: Tabs: поправить мерцание контента вкладки при переходе на новую

### ISSUE THREAD

**Issue by neretin-trike** [salute-developers/plasma#114]
При клике на буквы таба рендер контента происходит со второго раза.
Пример: https://codesandbox.io/s/plasma-web-example-forked-030dlc?file=/src/App.js

**Comment by Yeti-or** [comment]
Нужно обновить версию plasma-web:


Например, на версию: `@salutejs/plasma-web@1.120.0`

Обратите внимание что неймспейс поменялся;


Пример: https://codesandbox.io/s/plasma-web-example-forked-d7elnq?file=/src/App.js
