### ISSUE TITLE
plasma-temple: export DeviceComponent

### ISSUE THREAD

**Issue by VladimirGLukin** [salute-developers/plasma#116]
Предлагается поддержать экспорт DeviceComponent в plasma-temple и добавить соответствующее описание в документацию

**Comment by Yeti-or** [comment]
Кажется смысла в экспорте этого компонента нет, это внутренне устройство <PlasmaApp />; и работает только на клиенте (CreateReactApp например);
При этом есть публичный   [detectDevice](https://github.com/salute-developers/plasma/blob/master/packages/plasma-ui/src/utils/deviceDetection.ts#L75)
или [DeviceThemeProvider](https://github.com/salute-developers/plasma/blob/master/packages/plasma-ui/src/components/Device/DeviceDetection.tsx#L65)

Документация: 

https://plasma.sberdevices.ru/ui/functions/utils#detectdevice
https://plasma.sberdevices.ru/ui/device
https://plasma.sberdevices.ru/ui/components/devicethemeprovider/
