### ISSUE TITLE
Корректировка Image для устранения паразитного места под картинкой ( PLASMA-1962 )

### ISSUE THREAD

**Issue by DetiToDeti** [salute-developers/plasma#157]
Предлагаю добавить    
vertical-align: top; 
в  const StyledImg = styled.img<RatioProps>`
для устранения возникающего лишнего места под картинкой
это можно заметить закруглив углы у дива для Image

**Comment by PetePearl** [comment]
Возможно правильнее у картинки явно указать `display: block;`

**Comment by Yeti-or** [comment]
<img width="480" alt="Screenshot 2023-04-05 at 14 25 51" src="https://user-images.githubusercontent.com/1813468/230067003-6f62cf3e-28c9-41ff-9cec-316349cb9f2d.png">

паразитного места не обнаружено

если можете привести пример переоткройте пожалуйста задачу
