### ISSUE TITLE
plasma-ui: Увеличить handle в шторке

### ISSUE THREAD

**Issue by MishaKazakov** [salute-developers/plasma#219]
Сейчас есть проблема handle в шторке очень маленький за него тяжело ухватиться.

сейчас он такого размера. и только за эту часть можно ухватится
<img width="419" alt="Screen Shot 2022-11-14 at 5 26 06 PM" src="https://user-images.githubusercontent.com/33093997/201649100-0de37d1d-6ed8-4bf3-8d1e-6a3aa228b6fc.png">

можно сделать, чтобы визуально handle был таким же, но можно было ухватиться за всю ширину шторки. Так это работает в айос
<img width="431" alt="Screen Shot 2022-11-14 at 5 28 41 PM" src="https://user-images.githubusercontent.com/33093997/201649419-607067ae-2bc2-4527-bd34-1436716b623b.png">

**Comment by Yeti-or** [comment]
<img width="415" alt="Screenshot 2022-11-17 at 14 41 20" src="https://user-images.githubusercontent.com/1813468/202437155-4bdb2caa-1da9-4357-ab5d-c7da5410b699.png">
@MishaKazakov  мы недавно его увеличивали вот так

cc @gibushnev

**Comment by MishaKazakov** [comment]
О тогда надо обновить плазму. Спасибо
