### ISSUE TITLE
plasma-ui: Двоится placeholder в Input TextField ( PLASMA-1766 )

### ISSUE THREAD

**Issue by MishaKazakov** [salute-developers/plasma#246]
На samsung galaxy s21 двоится placeholder, когда нет значений.

<img width="211" alt="Screen Shot 2022-11-25 at 9 16 11 PM" src="https://user-images.githubusercontent.com/33093997/204014184-274a4d47-ae46-4c19-8138-e0f87abe21f8.png">

**Comment by Yeti-or** [comment]
@MishaKazakov можешь версию android сказать

**Comment by MishaKazakov** [comment]
@Yeti-or 13 андроид

**Comment by Yakutoc** [comment]
@MishaKazakov Привет подскажи пожалуйста какой браузер использовался?

**Comment by Yeti-or** [comment]
@MishaKazakov и версия plasma а то у нас не выходит воспроивести пока нигде

**Comment by MishaKazakov** [comment]
> @MishaKazakov Привет подскажи пожалуйста какой браузер использовался

Chrome 107.0.0.0

> @MishaKazakov и версия plasma а то у нас не выходит воспроизвести пока нигде

1.137.0

**Comment by Yakutoc** [comment]
@MishaKazakov Привет, у нас пока не получается воспроизвести такое поведение. 

У вас есть возможность сделать пример, как в этом #257 issue ?
