### ISSUE TITLE
Нельзя использовать Header с ScreensContainer

### ISSUE THREAD

**Issue by yuriymayorov** [salute-developers/plasma#29]
**Describe the bug**
Ошибка при использовании Header с ScreensContainer:
Uncaught Error: Assistant context is not provided

**Node, NPM and package versions**
`    "@salutejs/plasma-temple": "^1.68.2",
    "@salutejs/plasma-ui": "^1.104.1",`

**To Reproduce**
Инициализировать приложение через ScreensContainer и в Screen вызвать `const header = useHeaderProps({});`

**Expected behavior**
Ошибка не появляется и Header инициализируется

**Additional context**
````

**Comment by sinnakain** [comment]
+1, не работает.
Пожалуйста, почините.

**Comment by kvpolyanskiy** [comment]
Компонент `Header` в пакете `salutejs/plasma-temple` это часть функционала `PlasmaApp`, поэтому он не работает в связке с компонентом `ScreenContainer`, в  данном случае рекомендуется использовать компонент `Header` из пакета `salutejs/plasma-ui`.

**Comment by kvpolyanskiy** [comment]
Также можно обновится  до версии `@salutejs/plasma-temple@1.72.1`, в ней указанной ошибки быть не должно, но в любом случае компонент Header из пакета `@salutejs/plasma-temple`, работает только в связке с `PlasmaApp` или начиная с версии `1.72.1` с `ScreensContainer`

**Comment by Yeti-or** [comment]
Если проблема всё ещё не решена откройте issue заново
