### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by Yakutoc** [salute-developers/plasma#872]
# Как должен выглядеть наши `CHANGELOG`

## Labels 

именно вокруг них строится логика категоризации наших изменений которые хотим отразить в `CHANGELOG`

## Пример

Есть PR в котором мы добавили новый компонент Dropdown  

<img width="1121" alt="Screenshot 2023-12-01 at 14 16 07" src="https://github.com/salute-developers/plasma/assets/2895992/5544934c-cb18-4515-ae89-5fefadf9c84c">

На выходе мы получим такой результат который будет добавлен в описание для **release PR** 

```md
## Components

### Dropdown

- Удален из библиотеки plasma-hope
- Добавлена реализация на новой архитектуре в plasma-new-hope
- Добавлены сборки компонента для старых библиотек plasma-web, plasma-b2c

```

## Как работает? 

Для генерации CHANGELOG используется action -`mikepenz/release-changelog-builder-action@v4.1.0`.

Этот  action собирает все влитые в dev PR's и на основе **описанных** в конфигурации labels создает категории по которым и создает CHANGELOG.

**!!!ВАЖНО!!!**  **Label** не описаный в конфигурации попадают в **Uncategorized**.

В целом шаблон выглядит так 

```md

## Категория

### Заголовок (например Dropdown)

- тут текст резюме внесенных изменений 

 
Заголовок PR (URL PR) (например: feat: add Dropdown (https://github.com/PoligonSa/plasma-sandbox/pull/265))

```

**Comment by kayman233** [comment]
Основной вопрос конечно в том, что делать в случае нескольких лейблов. Не совсем понятно, насколько гибко вообще можем настраивать что-то такое через action
Наверное прямо здесь нужно обсудить сами категории?
Components, Icons, Infra, Uncategorized - есть в PR
Может еще нужно добавить лейбл по Theme Builder, что-то про Tokens(не уверен, что надо, мб это в Components лучше), Website. Наверное много разных можно придумать, и непонятно в целом, где грань попадания в свой отдельную категорию и Uncategorized

**Comment by Yakutoc** [comment]
про дублирую тут ) 

**Label - это категория**. По которой собирается однотипные pr's.   

Без **указанного** label, pr попадет в раздел "Uncategorized".

В моей голове это все выглядит так

У нас есть задача, например - "add header as separate components" 

В целом это же задача про добавить компонент и тут label components отлично подходит. 

А то что в рамках этой задачи была добавлена иконка, token, etc дело десятое. 

И это как раз должно отражаться в резюме, мол добавили то-то и т-то-то.

То есть категорию, label - **определяет** задача.

----

И к сожалению плагин который группирует pr's не умеет разбивать/извлекать контент исходя из этих labels.

----

> Мб всё-таки категории (второго уровня) отдать на откуп разработчикам, которые описывают PR?

Всегда есть вариант свести всё в  раздел "Uncategorized", без самого этого заголовка.

Но тогда нам руками придется заниматься группированием постов или писать свою логику для этого.

**Comment by kayman233** [comment]
так что насчет предложенных мною других лейблов? По-хорошему нужен список, который мы хоть как-то обсудили, как мне кажется

**Comment by Yakutoc** [comment]
- Components
- Infra
- Tokens
- Icons
- Uncategorized

Я исхожу из того какие задачи у нас были.
