### ISSUE TITLE
plasma-core: Переделать тесты hover/focused/pressed

### ISSUE THREAD

**Issue by Yeti-or** [salute-developers/plasma#886]
вместо передачи пропсов focused / pressed / hovered нужно делать соответсвующие события:

https://github.com/dmtrKovalenko/cypress-real-events

**Comment by denivladislav** [comment]
`focused` – в `realEvents` для фокуса нет отдельного события.
`pressed` – свойство deprecated, поэтому тест для него удален.
`hovered` –  тест не добавлен, поскольку для его реализации необходимо завязываться на конкретные стили:
https://github.com/dmtrKovalenko/cypress-real-events?tab=readme-ov-file#2-when-i-am-doing-cyrealhover-hovering-state-is-not-resetting-after-my-checks

`onClick` – в тест добавлен `realClick`.

PR:
https://github.com/salute-developers/plasma/pull/1388
